version: "3.7"
services:

  auth_db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
  
  
  auth:
    build:
      context: ./auth
    expose:
      - "5000"
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:auth.docker.localhost,traefik.backend=auth,traefik.backend.circuitbreaker.expression=NetworkErrorRatio()>0.5
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - rabbitmq 
      - auth_db 


  # auth_consumer:
  #   build:
  #     context: ./auth
  #   command: python -m massenger.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   restart: on-failure
  #   depends_on:
  #     - rabbitmq 
  #     - auth_db 


volumes:
  auth_data: